image: node:latest

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - node_modules/

build:
  stage: build
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - .next/

test:
  stage: test
  script:
    - npm test

deploy:
  stage: deploy
  script:
    - npm run start
  environment:
    name: production
  only:
    - master
