import Head from 'next/head'
import { Box, Button, TextField } from '@mui/material'
import { useState } from 'react'
import { useRouter } from 'next/router'
//import from connects.ts in api folder
import { authAndReturnUser } from '../api/connects'
import Link from 'next/link'

export default function Login() {


    const [username, setUsername] = useState('')
    const [password, setPassword] = useState('')


    const router = useRouter()

    async function login() {
        try {
            const user = await authAndReturnUser(username, password)
            console.log(user)
            router.push('/dashboard')
        }
        catch (error) {
            console.log(error)
        }
    }


    return (
        <>
        <Head>
            <title>Programvareutvikling</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
            <div className="flex min-h-full items-center justify-center py-12 px-4 sm:px-6 lg:px-8">
            <div className="w-full max-w-md space-y-8">
                <img 
                    src='/logo2.svg' 
                    className="mx-auto h-18 w-auto"
                 />
                <div>
                    <h2 className="mt-6 text-center text-3xl font-bold tracking-tight text-gray-900">
                        Login in to your account
                    </h2>
                    <p className="mt-2 text-center text-sm text-gray-600">
                        Or{' '}
                        <Link href="/register" className="font-medium text-violet-600 hover:text-violet-700">
                            Don&apos;t have an account yet? Sign up here.
                        </Link>
                    </p>
                </div>
                <Box
                component="form"
                noValidate
                autoComplete="off">

                <div className="mt-8 space-y-3">

                    <TextField
                        className="relative block w-full appearance-none rounded-none rounded-t-md border border-gray-300 px-3 py-2 text-gray-900 placeholder-gray-500 focus:z-10 focus:border-violet-500 focus:outline-none focus:ring-violet-500 sm:text-sm"
                        id="username-input"
                        label="Username"
                        type="username"
                        autoComplete="current-password"
                        onChange={(e) => setUsername(e.target.value)}
                    />
                    <TextField
                        id="password-input"
                        label="Password"
                        type="password"
                        autoComplete="current-password"
                        onChange={(e) => setPassword(e.target.value)}
                        className="relative block w-full appearance-none rounded-none rounded-b-md border border-gray-300 px-3 py-2 text-gray-900 placeholder-gray-500 focus:z-10 focus:border-violet-500 focus:outline-none focus:ring-violet-500 sm:text-sm"
                    />
                </div>
            </Box>
                <button
                    className="group relative flex w-full justify-center rounded-md border border-transparent bg-violet-600 py-2 px-6 text-sm font-medium text-white hover:bg-violet-700 focus:outline-none focus:ring-2 focus:ring-violet-500 focus:ring-offset-2" 
                    onClick={login}>
                        Login
                </button>
            </div>
            </div>
        </main>
        </>
    )
}
