import Head from 'next/head'
import { Box, Button, TextField } from '@mui/material'
import { useState } from 'react'
import { useRouter } from 'next/router'
//import from connects.ts in api folder
import { authAndReturnUser } from '../api/connects'


import { pocketbase } from '../api/connects'

export default function Home() {

    const [username, setUsername] = useState('')
    const [password, setPassword] = useState('')

    const router = useRouter()

    const login = async () => {
        try {
            const user = await authAndReturnUser(username, password)
            console.log(user)
            router.push('/dashboard')
        }
        catch (error) {
            console.log(error)
        }
    }

    return (
        <>
        <Head>
            <title>Programvareutvikling</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
            <div className='flex flex-col items-center pt-40 gap-5'>
                <img src='/logo2.svg' alt='logo' width={200} height={200} />
                <p>
                    Logged in: {pocketbase.authStore.isValid.toString()}
                </p>
                <Box
                component="form"
                noValidate
                autoComplete="off">

                <div className='grid gap-3'>

                    <TextField
                        id="username-input"
                        label="Username"
                        type="username"
                        autoComplete="current-password"
                        onChange={(e) => setUsername(e.target.value)}
                    />
                    <TextField
                        id="password-input"
                        label="Password"
                        type="password"
                        autoComplete="current-password"
                        onChange={(e) => setPassword(e.target.value)}

                    />
                </div>
            </Box>
                <Button variant="outlined" className='w-20' onClick={login}>Login</Button>
            </div>
        </main>
        </>
    )
}
