import Head from 'next/head'
import { Box, Button, TextField } from '@mui/material'
import { useState } from 'react'
import { useRouter } from 'next/router'
//import from connects.ts in api folder
import { registerUser } from '../api/connects'
import Link from 'next/link'

export default function Register() {

  const [username, setUsername] = useState('')
  const [password, setPassword] = useState('')
  const [email, setEmail] = useState('')
  const [passwordConfirm, setConfirmPassword] = useState('')
  const [name, setName] = useState('')

  const router = useRouter()

  async function register() {
      try {
          const user = await registerUser(username, email, password, passwordConfirm, name)
          console.log(user)

          router.push('/dashboard')
      }
      catch (error) {
          console.log(error)
      }
  }


  return (
      <>
      <Head>
          <title>Programvareutvikling</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
          <div className='flex flex-col items-center pt-20 gap-5'>
            <div>
                <img
                className="mx-auto h-17 w-auto"
                src="./logo2.svg"
                alt="MuscleMates"
                />
                <h2 className="mt-6 text-center text-3xl font-bold tracking-tight text-gray-900">
                Sign in to your account
                </h2>
                <p className="mt-2 text-center text-sm text-gray-600">
                Or{' '}
                <Link href="/login" className="font-medium text-violet-600 hover:text-violet-700">
                    Already have an account? Click here to log in. 
                </Link>
                </p>
            </div>
              <Box
              component="form"
              noValidate
              autoComplete="off">

              <div className='grid gap-3'>

                  <TextField
                      id="username-input"
                      label="Username"
                      type="username"
                      autoComplete="current-password"
                      onChange={(e) => setUsername(e.target.value)}
                  />
                  <TextField
                      id="name-input"
                      label="Name"
                      type="name"
                      autoComplete="current-password"
                      onChange={(e) => setName(e.target.value)}
                  />
                  <TextField
                      id="email-input"
                      label="E-mail"
                      type="email"
                      autoComplete="current-password"
                      onChange={(e) => setEmail(e.target.value)}
                  />
                  <TextField
                      id="password-input"
                      label="Password"
                      type="password"
                      autoComplete="current-password"
                      onChange={(e) => setPassword(e.target.value)}

                  />
                  <TextField
                      id="confirmPassword-input"
                      label="Confirm Password"
                      type="password"
                      autoComplete="current-password"
                      onChange={(e) => setConfirmPassword(e.target.value)}
                  />
                  
              </div>
          </Box>
              <button
                className="group relative flex mb-5 justify-center rounded-md border border-transparent bg-violet-600 py-2 px-4 text-sm font-medium text-white hover:bg-violet-700 focus:outline-none focus:ring-2 focus:ring-violet-500 focus:ring-offset-2" 
                onClick={register}>
                    Register
                </button>
          </div>
      </main>
      </>
  )
}
