import Head from 'next/head'
import { Box, Button, TextField } from '@mui/material'
import { useState } from 'react'
import { useRouter } from 'next/router'
import { createProgram } from '../api/connects'
import { use } from 'react';
import { pocketbase } from '../api/connects';


export default function Dashboard() {
  const [userId, setUserId] = useState('')
  const [exercises, setExercises] = useState('')
  const [name, setName] = useState('')

  const router = useRouter()

  async function addProgram(){
    try{
      const program = await createProgram(userId, exercises, name)
      console.log(program)
      router.push('/dashboard')
    }
    catch (error){
      console.log(error)
    }
  }
  return (
    <>
      <Head>
          <title>Programvareutvikling</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
          <div className='flex flex-col items-center pt-40 gap-5'>
              <Box
              component="form"
              noValidate
              autoComplete="off">

              <div className='grid gap-3'>
                
              </div>
          </Box>
              <Button variant="outlined" className='w-25' onClick={addProgram}>Create Program</Button>
          </div>
      </main>
      </>)
}

  
  
